enum clientRoute {
  root = "/",
  login = "/login",
  createAccount = "/create-account",
  profile = "/profile",
  matchHistory = "/match-history",
  group = "/group",
  account = "/account",
  accountDetails = "/account-details",
  changePassword = "/change-password",
  approveMatches = "/approve-matches",
  joinGroup = "/join-group",
  createGroup = "/create-group",
  groupRequests = "/group-requests",
  joinCreateGroup = "/join-or-create-group",
  manageGroup = "/manage-group",
  addAdmin = "/add-admin",
  recordMatch = "/record-match",
  removeMembers = "/remove-members",
  deleteAccount = "/delete-account",
  forgottenPassword = "/forgotten-password",
  emailVerification = "email-verification",
}

export default clientRoute
